name: Publish and deploy

on:
  push: 
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: deploy
  cancel-in-progress: true

jobs:
  publish: 
    if: github.repository == 'teidesu/tei.su' # do not run on forks
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare
        env: 
            DONATE_PAGE_DATA: ${{ vars.DONATE_PAGE_DATA }}
        run: |
            echo "$DONATE_PAGE_DATA" > src/components/pages/PageDonate/data.json

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/teidesu/tei.su
          tags: type=sha
          flavor: latest=true
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - uses: teidesu/desu-deploy@main
        with:
          key: ${{ secrets.DEPLOY_KEY }}
          server: ${{ secrets.DEPLOY_SERVER }}
          wireguard: ${{ secrets.DEPLOY_WG }}
          service: teisu